type: chain
configs:
- type: on_mark
  key: state
  value: uncorrupted
  configs:
  - type: switch
    configs:
    - type: token_masking
      prob: 0.2
      min_tokens: 3
      num_tokens_prob: 0.2
      mask_token: (mask)
    - type: token_masking
      prob: 0.2
      min_tokens: 22
      num_tokens_prob: 0.1
      mask_token: (mask)
    probabilities: [0.5, 0.5]
- type: clip_length
