# short mask corruption
# mask 20% of all tokens in char mode
# at least 4 consecutive words, but on average
# 4 + 1 / 0.2 - 1 = 4 + 4 = 8 chars
type: mask_corruption
prob: 0.2
mask_token: <mask>
mode:
  type: char
  min: 4
  prob: 0.2
