# long mask corruption
# mask 20% of all tokens in word mode
# at least 12 consecutive words, but on average
# 12 + 1 / 0.2 - 1 = 12 + 4 = 16 words
type: mask_corruption
prob: 0.2
mask_token: <mask>
mode:
  type: word
  min: 12
  prob: 0.2
