type: chain
configs:
- file(env(CLEAN_CONFIG:clean_normalize.yaml))
- type: switch
  configs:
  - type: chain
    configs:
      - file(de/spelling_corruption.yaml)
      - file(whitespace/whitespace_corruption.yaml)
      - type: mark
        key: state
        value: corrupted
  - type: mark
    key: state
    value: uncorrupted
  probabilities: [0.8, 0.2]
- type: language_dropout
  prob: 0.25
