type: switch
configs:
  - type: whitespace_corruption
    insert_whitespace_prob: 0.05
    delete_whitespace_prob: 0.2
  - type: full_whitespaces
  - type: no_whitespaces
probabilities:
  - 0.8
  - 0.1
  - 0.1
