type: encoder_decoder_with_head
memory: encoder
encoder_embedding:
  type: standard
  embedding_dim: env(DIM:768)
  dropout: 0.1
  mode: norm
  positional_embeddings: sinusoidal
  max_length: eval(env(MAX_LENGTH:512) * 4)
  group_embeddings: before_pos
  group_name: code_point_groups
  group_padding_mask: padding_mask
  group_lengths: lengths
encoder:
  type: transformer
  dim: env(DIM:768)
  num_layers: eval(round(env(NUM_LAYERS:12) * 2/3))
  heads: eval(env(DIM:768) // 64)
  ffw_dim: eval(env(DIM:768) * 4)
  with_pos: attention
  dropout: 0.1
decoder_embedding:
  type: standard
  embedding_dim: env(DIM:768)
  dropout: 0.1
  mode: norm
  positional_embeddings: sinusoidal
  max_length: eval(env(MAX_LENGTH:512) * 4)
decoder:
  type: transformer
  memories: [encoder]
  dim: env(DIM:768)
  num_layers: eval(round(env(NUM_LAYERS:12) * 1/3))
  heads: eval(env(DIM:768) // 64)
  ffw_dim: eval(env(DIM:768) * 4)
  with_pos: attention
  dropout: 0.1
