experiment:
  name: env(EXPERIMENT_NAME:multi_byte_large)

seed: 22

input_tokenizer: file(tokenizers/bpe_multi.yaml)
output_tokenizer: file(tokenizers/bpe_multi.yaml)

model: file(models/transformer.yaml)

train:
  mixed_precision: env(MIXED_PRECISION:true)
  mixed_precision_dtype: env(MIXED_PRECISION_DTYPE:fp16)
  clip_grad_norm: env(CLIP_GRAD_NORM:1.0)
  num_epochs: env(NUM_EPOCHS:1)
  eval_interval: eval(1 / env(EVAL_PER_EPOCH:20))
  log_interval: eval(1 / env(LOG_PER_EPOCH:1000))
  step_interval: eval(1 / env(STEP_PER_EPOCH:1000))
  loss: file(losses/env(LOSS:ce).yaml)
  optimizer:
    type: adamw
    lr: env(LR:0.0001)
    weight_decay: 0.01
  lr_scheduler:
    type: multi_step_with_warmup
    warmup_steps: env(WARMUP_STEPS:0.01)
    steps: [0.5, 0.75, 0.9]
    factors: [0.5, 0.2, 0.1]
  metrics:
    text_generation:
      max_items: 8
  data:
    strategy: weighted
    shuffle: true
    sort: true
    limit: env(TRAIN_LIMIT:null)
    max_length: eval(env(MAX_LENGTH:512) // 2)
    max_length_scheduler:
      type: multi_step
      steps: [0.75]
      factors: [2.0]
    buffer_size: env(BUFFER_SIZE:512)
    prefetch_factor: env(PREFETCH_FACTOR:512)
    num_threads: eval(env(THREADS:None) or len(os.sched_getaffinity(0)) // 2)
    batch_limit: eval(env(MAX_LENGTH:512) * env(BATCH_LIMIT:32))
    batch_limit_type: padded_item_size
    default_language: (lang:unk)
    pipeline:
      tokenizer: file(tokenizers/bpe_multi.yaml)
      labeling:
        type: sequence_generation
        tokenizer: file(tokenizers/bpe_multi.yaml)
      postprocessing: file(postprocessings/masking.yaml)
    sources: file(data_sources.yaml)
    val: env(VAL_LIMIT:10000)
