experiment:
  name: env(EXPERIMENT_NAME)

seed: 22

input_tokenizer: file(tokenizers/byte.yaml)
output_tokenizer: file(tokenizers/bpe.yaml)

model:
  type: encoder_decoder_with_head
  memory: encoder
  encoder_embedding:
    type: standard
    embedding_dim: env(DIM:512)
    dropout: 0.1
    mode: add_norm
    positional_embeddings: sinusoidal
    max_length: eval(2 * env(MAX_LENGTH:512))
  encoder:
    type: grouping
    group_first: true
    group_name: code_point_groups
    group_padding_mask: padding_mask
    group_lengths: lengths
    encoder:
      type: transformer
      dim: env(DIM:512)
      num_layers: eval(round(env(NUM_LAYERS:12) * 2/3))
      heads: eval(env(DIM:512) // 64)
      ffw_dim: eval(env(DIM:512) * 4)
      dropout: 0.1
  decoder_embedding:
    type: standard
    embedding_dim: env(DIM:512)
    dropout: 0.1
    mode: add_norm
    positional_embeddings: sinusoidal
    max_length: eval(2 * env(MAX_LENGTH:512))
  decoder:
    type: transformer
    memories: [encoder]
    dim: env(DIM:512)
    num_layers: eval(round(env(NUM_LAYERS:12) * 1/3))
    heads: eval(env(DIM:512) // 64)
    ffw_dim: eval(env(DIM:512) * 4)
    dropout: 0.1

train:
  mixed_precision: env(MIXED_PRECISION:true)
  mixed_precision_dtype: env(MIXED_PRECISION_DTYPE:fp16)
  clip_grad_norm: env(CLIP_GRAD_NORM:1.0)
  num_epochs: env(NUM_EPOCHS:3)
  eval_interval: eval(1 / env(EVAL_PER_EPOCH:10))
  log_interval: eval(1 / env(LOG_PER_EPOCH:100))
  loss: file(losses/env(LOSS:ce).yaml)
  optimizer:
    type: adamw
    lr: env(LR:0.0001)
    weight_decay: 0.01
  lr_scheduler:
    type: cosine_with_warmup
    warmup_steps: env(WARMUP_STEPS:0.01)
  metrics:
    text_generation:
      max_items: 4
      eos_token: <eos>
  data:
    strategy: weighted
    shuffle: true
    sort: true
    buffer_size: env(BATCH_LIMIT:32)
    prefetch_factor: env(PREFETCH_FACTOR:2048)
    num_threads: eval(env(THREADS:None) or len(os.sched_getaffinity(0)) // 2)
    batch_limit: eval(env(MAX_LENGTH:1024) * env(BATCH_LIMIT:32))
    batch_limit_type: padded_item_size
    pipeline:
      tokenizer: file(tokenizers/byte.yaml)
      ignore_special_tokens: false
      preprocessing: file(preprocessings/text_corruption.yaml)
      labeling:
        type: sequence_generation
        tokenizer: file(tokenizers/bpe.yaml)
    sources:
      - type: file
        path: abspath(env(DATA_FILE))
        temp_dir: abspath(env(TMP))
        language: en
    val: env(VAL_LIMIT:10000)
